AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Hollyhook: CFN Template to create am IAM Role EC2 Instance

Metadata:
  TemplateName: iam-role-stack.yaml
  TemplateType: IAM Role / IAM Policy
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Hollyhook
  Modification History:
    - 1.0.0  - Jan 27, 2024   -- Initial Version 
  Resources: 
    - IAM Role
    - IAM Policy Attached To The Role
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: 'Project And Environment:'
      Parameters: 
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
    #################################### KMS Key ###################################################
    - Label: 
        default: 'KMS Configuration:'
      Parameters: 
      - KmsMasterKeyId
    #################################### IAM Roles #################################################
    - Label: 
        default: 'IAM Roles :'
      Parameters: 
      - EC2RoleBaseName
    ParameterLabels:
      ########################################### Project Name and Environment #######################
      ProjectName:
        default: 'Project Name.'
      Environment:
        default: 'Environment Name.'
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref"
      GitHubURL: 
        default: "GitHub repository URL"
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA: 
        default: "GitHub Workflow Run Number."
      GitHubRepository:
        default: "GitHub repository name."
      CiBuild:
        default: "Feature branch Ci Build"
      ################################## IAM Roles #################################################
      EC2RoleBaseName: 
        default: "EC2 IAM Role base name"
Parameters:
  ################## Project Name and Environment ##################################################
  ProjectName:
    Default: hollyhook
    Description: 'The Project Name.'
    Type: String
    MinLength: 4
    MaxLength: 30
    AllowedPattern: '[a-z]*'
    ConstraintDescription: 'The length should be between 5 and 30, must contain only lowercase alphabets.'
  Environment:
    Default: devl
    Description: 'The Environment Name.'
    Type: String
    AllowedValues: ['devl', 'test', 'prod']
    ConstraintDescription: 'The Environment must be devl / test or prod'
 #################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-hibiscus
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ###################################### KMS #######################################################
  KmsMasterKeyId:
    Default: "arn:aws:kms:us-east-1:237376087602:key/f7eb118d-f1d2-4d70-a046-dfada470840e"
    Description: "The KMS Key Id Used For Encryption."
    Type: String
    MinLength: 75
    MaxLength: 75
    AllowedPattern: "[a-z:/0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."  
  ###################################### IAM Roles #################################################
  EC2RoleBaseName:
    Type: String
    Default: iam-role
    Description: "The Base name of the EC2 IAM Role"
Resources:
  ###################################### EC2 Role ##################################################
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${EC2RoleBaseName}-${Environment}${CiBuild}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
      - !Sub "arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess"
      Policies:
        - PolicyName: !Sub '${ProjectName}-allow-kms-${Environment}${CiBuild}'
          PolicyDocument:
            Statement:
            - Sid: AllowKMSDecryption
              Effect: Allow
              Action: 
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:GenerateDataKeyPair
              Resource:
              - !Ref KmsMasterKeyId
      Tags:
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
Outputs:
  EC2RoleArn:
    Description: The Arn of the EC2 Instance Role
    Value: !GetAtt EC2Role.Arn
  EC2RoleName:
    Description: The Name of the EC2 Instance Role
    Value: !Ref EC2Role
