AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Hollyhock: Root Stack Template To create EC2 Auto Scaling Group behind an Application Load Balancer with scaling policy.

Metadata:
  TemplateName: holly-root-stack.yaml
  TemplateType: VPC with public and private subnets / Security Group
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Hollyhock
  Modification History:
    - 1.0.0  - Jan 27, 2024   -- Initial Version
  Resources: 
    - One Custom VPC with public and private subnets.
    - Security Group
    - EC2 Launch Template
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label:
        default: "Project Name And Environment:"
      Parameters:
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
    #################################### Code Repository Bucket ####################################
    - Label:
        default: "Code Repository S3 Bucket:"
      Parameters:
      - CodeRepositoryS3Bucket
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
        - KmsMasterKeyId
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref."
      GitHubURL:
        default: "GitHub URL."
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA:
        default: "GitHub SHA"
      GitHubRepository:
        default: "GitHub Repository."
      CiBuild:
        default: "Ci Build."
      ################################## Code Repository Bucket ####################################
      CodeRepositoryS3Bucket:
        default: "Code Repository S3 Bucket."
      ################################## KMS Key ###################################################
      KmsMasterKeyId:
        default: "KMS Key Id."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: hollyhock
    Description: "The Project Name for which the custom resource will be used."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### Code Repository S3 Bucket #################################
  CodeRepositoryS3Bucket:
    Default: subhamay-projects-repository-237376087602-devl-us-east-1
    Description: "S3 Bucket Storing The Lambda Code."
    Type: String
    MinLength: 10
    MaxLength: 63
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 63, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  ###################################### KMS Key ###################################################
  KmsMasterKeyId:
    Default: "arn:aws:kms:us-east-1:237376087602:key/f7eb118d-f1d2-4d70-a046-dfada470840e"
    Description: "The KMS Key Id Used For Encryption."
    Type: String
    MinLength: 75
    MaxLength: 75
    AllowedPattern: "[a-z:/0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 0101-hollyhock-cft
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ####################################### EC2 #######################################################
  # ImageId:
  #   Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
  #   Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
Resources:
  ###################################### VPC #######################################################
  HollyhockVPCStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub 'https://${CodeRepositoryS3Bucket}.s3.amazonaws.com/${GitHubRepository}/${GitHubSHA}/cft/nested-stacks/vpc-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GitHubRef: !Ref GitHubRef
        GitHubURL: !Ref GitHubURL
        GitHubWFRunNumber: !Ref GitHubWFRunNumber
        GitHubSHA: !Ref GitHubSHA
        GitHubRepository: !Ref GitHubRepository
        CiBuild: !Ref CiBuild
      TimeoutInMinutes: 5
  ###################################### Security Group ############################################
  HollyhockEC2SecurityGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub 'https://${CodeRepositoryS3Bucket}.s3.amazonaws.com/${GitHubRepository}/${GitHubSHA}/cft/nested-stacks/security-group-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GitHubRef: !Ref GitHubRef
        GitHubURL: !Ref GitHubURL
        GitHubWFRunNumber: !Ref GitHubWFRunNumber
        GitHubSHA: !Ref GitHubSHA
        GitHubRepository: !Ref GitHubRepository
        CiBuild: !Ref CiBuild
        VpcId: !GetAtt HollyhockVPCStack.Outputs.VpcId
        ALBSecurityGroupName: 'alb-sg'
        EC2SecurityGroupName: 'ec2-sg'
        ALBSecurityGroupDescription: !Sub "${ProjectName} Security Group For Auto Scaling Group."
        EC2SecurityGroupDescription: !Sub "${ProjectName} Security Group For EC2 Instance."
      TimeoutInMinutes: 5
  ###################################### IAM Role ##################################################
  HollyhockIAMRole:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub 'https://${CodeRepositoryS3Bucket}.s3.amazonaws.com/${GitHubRepository}/${GitHubSHA}/cft/nested-stacks/iam-role-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GitHubRef: !Ref GitHubRef
        GitHubURL: !Ref GitHubURL
        GitHubWFRunNumber: !Ref GitHubWFRunNumber
        GitHubSHA: !Ref GitHubSHA
        GitHubRepository: !Ref GitHubRepository
        CiBuild: !Ref CiBuild
        KmsMasterKeyId: !Ref KmsMasterKeyId
        EC2RoleBaseName: "ec2-role"
      TimeoutInMinutes: 5
  ###################################### EC2 Launch Template #######################################
  HollyhockEC2LaunchTemplate:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub 'https://${CodeRepositoryS3Bucket}.s3.amazonaws.com/${GitHubRepository}/${GitHubSHA}/cft/nested-stacks/ec2-launch-template-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GitHubRef: !Ref GitHubRef
        GitHubURL: !Ref GitHubURL
        GitHubWFRunNumber: !Ref GitHubWFRunNumber
        GitHubSHA: !Ref GitHubSHA
        GitHubRepository: !Ref GitHubRepository
        CiBuild: !Ref CiBuild
        # VpcId: !GetAtt HollyhockVPCStack.Outputs.VpcId
        EC2SecurityGroupId: !GetAtt HollyhockEC2SecurityGroup.Outputs.EC2SecurityGroupId
        EC2RoleName: !GetAtt HollyhockIAMRole.Outputs.EC2RoleName
      TimeoutInMinutes: 5
  ###################################### EC2 Web Servers ###########################################
  HollyhockEC2WebServerA:
    Type: AWS::EC2::Instance
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties: 
      LaunchTemplate:
        LaunchTemplateId: !GetAtt HollyhockEC2LaunchTemplate.Outputs.LaunchTemplateId
        Version: !GetAtt HollyhockEC2LaunchTemplate.Outputs.LaunchTemplateLatestVer
      SubnetId: !GetAtt HollyhockVPCStack.Outputs.PublicSubnet1AId
      Tags: 
      - Key: Name
        Value: "webserver-A"
  HollyhockEC2WebServerB:
    Type: AWS::EC2::Instance
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties: 
      LaunchTemplate:
        LaunchTemplateId: !GetAtt HollyhockEC2LaunchTemplate.Outputs.LaunchTemplateId
        Version: !GetAtt HollyhockEC2LaunchTemplate.Outputs.LaunchTemplateLatestVer
      SubnetId: !GetAtt HollyhockVPCStack.Outputs.PublicSubnet1BId
      Tags: 
      - Key: Name
        Value: "webserver-B"
  ###################################### Application Load Balancer #################################
  HollyhockApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      # EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic: String
      IpAddressType: ipv4
      # LoadBalancerAttributes: 
      #   - LoadBalancerAttribute
      Name: 
        'Fn::Transform':
          Name: 'String'
          Parameters: 
            InputString: !Sub "${ProjectName}-alb-${Environment}-${AWS::Region}${CiBuild}"
            Operation: Sqeeze
            CiBuild: !Ref CiBuild
            StrLen: 32
      Type: application
      Scheme: internet-facing
      SecurityGroups: 
        - !GetAtt HollyhockEC2SecurityGroup.Outputs.ASGSecurityGroupId
      Subnets: 
        - !GetAtt HollyhockVPCStack.Outputs.PublicSubnet1AId
        - !GetAtt HollyhockVPCStack.Outputs.PublicSubnet1BId
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
  ###################################### ELB Target Group ##########################################
  HollyhockELBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Name: 
        'Fn::Transform':
          Name: 'String'
          Parameters: 
            InputString: !Sub "${ProjectName}-tg-${Environment}-${AWS::Region}${CiBuild}"
            Operation: Sqeeze
            CiBuild: !Ref CiBuild
            StrLen: 32
      VpcId: !GetAtt HollyhockVPCStack.Outputs.VpcId
      Port: 80
      Protocol: HTTP
      IpAddressType: ipv4
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /status/200
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetType: instance
      Targets: 
      - Id: !Ref HollyhockEC2WebServerA
        Port: 80
      - Id: !Ref HollyhockEC2WebServerB
        Port: 80
      # ProtocolVersion: String
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
  ###################################### Http Plain Listener #######################################
  HollyhockHttpPlainListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref HollyhockELBTargetGroup
      LoadBalancerArn: !Ref HollyhockApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
Outputs:
  VpcId: 
    Description: VPC Id
    Value: !GetAtt HollyhockVPCStack.Outputs.VpcId
  PublicSubnet1AId: 
    Description: PublicSubnet1AId Id
    Value: !GetAtt HollyhockVPCStack.Outputs.PublicSubnet1AId
  PublicSubnet1BId: 
    Description: PublicSubnet1BId Id
    Value: !GetAtt HollyhockVPCStack.Outputs.PublicSubnet1BId
  PrivateSubnet1AId: 
    Description: PrivateSubnet1AId Id
    Value: HollyhockVPCStack.Outputs.PrivateSubnet1AId
  PrivateSubnet1BId: 
    Description: PrivateSubnet1BId Id
    Value: !GetAtt HollyhockVPCStack.Outputs.PrivateSubnet1BId
  ASGSecurityGroupId:
    Description: The Security Group Id of the ASG
    Value: !GetAtt HollyhockEC2SecurityGroup.Outputs.ASGSecurityGroupId
  EC2SecurityGroupId:
    Description: The Security Group Id of the EC2 instances
    Value: !GetAtt HollyhockEC2SecurityGroup.Outputs.EC2SecurityGroupId
  EC2IAMRoleName:
    Description: EC2 IAM Role Name
    Value: !GetAtt HollyhockIAMRole.Outputs.EC2RoleName
  EC2IAMRoleArn:
    Description: EC2 IAM Role Arn
    Value: !GetAtt HollyhockIAMRole.Outputs.EC2RoleArn
  InstanceProfileName:
    Description: EC2 Instance Profile Name
    Value: !GetAtt HollyhockEC2LaunchTemplate.Outputs.InstanceProfileName
  InstanceProfileArn:
    Description: EC2 Instance Profile Arn
    Value: !GetAtt HollyhockEC2LaunchTemplate.Outputs.InstanceProfileArn
  LaunchTemplateId: 
    Description: The Launch Template Id
    Value: !GetAtt HollyhockEC2LaunchTemplate.Outputs.LaunchTemplateId
  LaunchTemplateLatestVer: 
    Description: The Launch Latest Version
    Value: !GetAtt HollyhockEC2LaunchTemplate.Outputs.LaunchTemplateLatestVer
  WebServerAEC2InstanceId:
    Description: WebServer A Instance Id
    Value: !Ref HollyhockEC2WebServerA
  WebServerBEC2InstanceId:
    Description: WebServer B Instance Id
    Value: !Ref HollyhockEC2WebServerB
  ELBTargetGroupArn:
    Description: The Arn of the ELB Target Group
    Value: !Ref HollyhockELBTargetGroup
  ApplicationLoadBalancerArn:
    Description: The Arn of Application Load Balancer
    Value: !GetAtt HollyhockApplicationLoadBalancer.LoadBalancerArn
  ApplicationLoadBalancerDNSName:
    Description: The DNS Name of the Application Load Balancer
    Value: !GetAtt HollyhockApplicationLoadBalancer.DNSName
  ApplicationLoadBalancerName:
    Description: The Name of the Application Load Balancer
    Value: !GetAtt HollyhockApplicationLoadBalancer.LoadBalancerName
  ApplicationLoadBalancerFullName:
    Description: The Full Name of the Application Load Balancer
    Value: !GetAtt HollyhockApplicationLoadBalancer.LoadBalancerFullName
